#!/bin/bash
#
# toggles the trash flag on the thread, unsetting the inbox tag if set as
# required by gmail
#
# it can be used also to undo, if the thread is trashed it removes the trash
# flag and if it was in inbox (known beacuse the _inbox tag is set) then it
# restores the inbox flag
#
# This should work for gmail It is cleaner if you do not synchronize the local
# tag _inbox to the remote gmail account. With gmailieer you can add _inbox to
# the ignore tags local set

has_tag() {
	notmuch search "thread:$2 and tag:$1"
}

if [[ $(has_tag trash $1) && $(has_tag inbox $1) ]]; then
	# Happens whe you receive a new mail in a thread that you already trashed
	tags="+trash +_inbox -inbox"
elif [[ ! $(has_tag trash $1) ]]; then
	tags="+trash"
	if [[ $(has_tag inbox $1) ]]; then
		tags="$tags +_inbox -inbox"
	fi
else
	tags="-trash"
	if [[ $(has_tag _inbox $1) ]]; then
		tags="$tags -_inbox +inbox"
	fi
fi

notmuch tag $tags "thread:$1"
