#!/bin/bash

# Example locker script -- demonstrates how to use the --transfer-sleep-lock
# option with i3lock's forking mode to delay sleep until the screen is locked.

## CONFIGURATION ##############################################################

# Options to pass to i3lock
i3lock_options="-e -f -t -i $HOME/.config/i3/screenlock.png"

# Run before starting the locker
pre_lock() {
    #mpc pause
    return
}

# Run after the locker exits
post_lock() {
    return
}

###############################################################################

pre_lock

# XSS_SLEEP_LOCK_FD is the file descriptor of the delay lock obtained from the
# login manager, if the reason for lockingist that the system is preparing to go
# to sleep

# We set a trap to kill the locker if we get killed, then start the locker and
# wait for it to exit. The waiting is not that straightforward when the locker
# forks, so we use this polling only if we have a sleep lock to deal with.
if [[ -e /dev/fd/${XSS_SLEEP_LOCK_FD:--1} ]]; then
    kill_i3lock() {
        pkill -xu $EUID "$@" i3lock
    }

    trap kill_i3lock TERM INT

    # we have to make sure the locker does not inherit a copy of the lock fd
    i3lock $i3lock_options {XSS_SLEEP_LOCK_FD}<&-

    # now close our fd (only remaining copy) to indicate we're ready to sleep
    exec {XSS_SLEEP_LOCK_FD}<&-

	# we now wait for screen to be unlocked
	# this loop waits while the process i3lock exists (sending signal 0 sends no
	# signal, but errors are checked)
    while kill_i3lock -0; do
        sleep 0.5
    done
else
    trap 'kill %%' TERM INT
	# -n for i3lock not forking, so we can wait for it
    i3lock -n $i3lock_options &
	# wait for screen unlock
    wait
fi

post_lock
