#!/bin/bash

delete=0
program_name=$0

install_files() {
	local file
	while (( $# )); do
		file="$1"

		if test -e "$HOME/.$file" -a ! -L "$HOME/.$file"; then
			if [ $delete -eq 0 ]; then
				mv -Tv "$HOME/.$file" "$HOME/.$file.old"
			else
				rm -rfv "$HOME/.$file"
			fi
		fi

		ln -sfTv "$PWD/$file" "$HOME/.$file"
		shift
	done
}

usage() {
	echo "$program_name [-d] [-h]"
	echo
	printf "\t-d delete old files instead of creating backups\n"
	printf "\t-h: shows this help message\n"
	printf "\n"
}

while getopts "dh" o; do
    case "${o}" in
        h)
			usage
			exit 0
			;;
		d)
			delete=1
            ;;
        *)
            usage
			exit 0
            ;;
    esac
done

git submodule update --init

config_files="$(ls -d * | grep -v "config\|README\|install") $(ls -d config/*)"

install_files $config_files
