#!/bin/bash

#export TERMCMD=sakura
#export TERMCMD=urxvt
export TERMCMD=st
export GTK_THEME=Adwaita
#export GDK_SCALE=0.75
#export GDK_DPI_SCALE=0.75
#if [ "$DESKTOP_SESSION" = "i3" ]; then
#	xrandr --dpi 168
#fi

if [ -f "$HOME/.profile" ]; then
	source "$HOME/.profile"
fi

