#!/bin/bash

if [ -f "$HOME/.bashrc" ]; then
	source "$HOME/.bashrc"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

#export TERMCMD=sakura
export TERMCMD=urxvt
#export GDK_SCALE=0.75
#export GDK_DPI_SCALE=0.75
#if [ "$DESKTOP_SESSION" = "i3" ]; then
#	xrandr --dpi 168
#fi
