#!/bin/bash

current=$(autorandr | grep current | awk '{print $1}')

if test -x ~/.config/autorandr/$current/postswitch; then
	~/.config/autorandr/$current/postswitch
fi

i3-msg restart
sleep 0.5
if pgrep compton; then
	pkill -USR1 compton
fi


exit 0
