#!/bin/bash

detected=$(autorandr | grep detected | awk '{print $1}')

if test -x ~/.config/autorandr/$detected/postswitch; then
	~/.config/autorandr/$detected/postswitch
fi

i3-msg restart
if pgrep compton; then
	pkill -USR1 compton
fi


exit 0
