#!/bin/bash 

row=$(swaymsg -t get_tree | jq  -r '
    ..
    | objects
    | select(.type == "workspace")
	| (if .name == "__i3_scratch" then "scratch" else .name end) as $ws
    | ..
    | objects
    | select(has("app_id"))
    | (if .focused == true then "*" else " " end) as $asterisk
	| (if .shell == "xwayland" then .window_properties.class else .app_id end) as $app
	| "[\($ws)] \($asterisk) <span weight=\"bold\">\($app)</span>  - \(.name) <!-- \(.id) -->\u0000icon\u001f\(.app_id)"' \
| sed 's/&/&amp;/g' \
| rofi -dmenu -i -show-icons -markup-rows)
#| wofi -d -I -m)


if [ ! -z "$row" ]
then
    winid=$(echo "$row" | sed 's/.*<!-- \([0-9]*\) -->.*/\1/')
	swaymsg "[con_id=$winid] focus"
fi

