#!/bin/bash 

row=$(swaymsg -t get_tree | jq  -r '
    ..
    | objects
    | select(.type == "workspace")
	| (if .name == "__i3_scratch" then "scratch" else .name end) as $ws
    | ..
    | objects
    | select(has("app_id"))
    | (if .focused == true then "*" else " " end) as $asterisk
	| (if .shell == "xwayland" then .window_properties.class else .app_id end) as $app
	| "[\($ws)] \($asterisk) \($app)  - \(.name)\u0000icon\u001f\($app)"' \
	| sed 's/&/&amp;/g' \
	| fuzzel --dmenu)
	
if [ ! -z "$row" ]
then
    winid=$(echo "$row" | sed 's/.*<!-- \([0-9]*\) -->.*/\1/')
	swaymsg "[con_id=$winid] focus"
fi

