#!/bin/bash

DPMS_STATUS=$(xset q | grep -oP 'DPMS is \K([a-zA-Z]+)')
SB_SEG=$(xset q | grep -A2 "Screen Saver" | grep timeout | awk '{print $2}')
DPMS_TIMES=$(xset q | grep -A1 DPMS | grep Standby)
SSB_SEG=$(echo $DPMS_TIMES | awk '{print $2}')
SOFF_SEG=$(echo $DPMS_TIMES | awk '{print $6}')

if [ "$DPMS_STATUS" == "Enabled" ]; then
	full_text="on"
else
	full_text="<span foreground=\"red\">off</span>"
fi

full_text="$full_text ($(($SB_SEG / 60))/$(($SSB_SEG / 60))/$(($SOFF_SEG / 60)))"
short_text=$full_text

echo $full_text
echo $short_text
