#!/bin/bash

FW_FILE=~/.config/autorandr/laptop/focused_workspace

if [ -f ${FW_FILE} ]; then
	focused_workspace=$(cat ${FW_FILE})
else
	focused_workspace=$(i3-msg -t get_workspaces | jq '.[] | select(.focused==true) | .name')
fi

i3-msg "restart"
i3-msg "workspace $focused_workspace"

exit 0
