#!/bin/bash

if [ $# -lt 1 ]; then
	exit 0
fi

if [ ! -d $1 ]; then
	exit 0
fi

urls=$(xclip -o -sel clip -t x-special/gnome-copied-files 2>&1 /dev/null)
if test -z "$urls"; then
	exit 0
fi

files=$(printf "$urls" | awk '/file:\/\//{print $1}' | sed 's/^file:\/\///')

cp --target-dir="$1" $files
