#!/bin/bash

LOGFILE=~/.config/autorandr/autorandr_log
echo "Runing global postswitch hook, current profile is: $AUTORANDR_CURRENT_PROFILE" >> $LOGFILE

feh --bg-fill ~/.config/i3/wallpaper.png

if pgrep compton; then
	pkill -USR1 compton
fi

echo "Ending autorandr postswitch hook" >> $LOGFILE

exit 0
