#!/bin/bash

source $HOME/.config/kanshi/scripts/utils

for w in $(active_workspaces_excluding 1 9 10)
do 
	swaymsg workspace $w, move workspace to DP-3 ;
done

for w in $(active_workspaces_including 1 9 10)
do 
	swaymsg workspace $w, move workspace to eDP-1 ;
done

swaymsg workspace 1
