#!/bin/bash

active_workspaces()
{
	echo $(swaymsg -t get_workspaces -p | grep -e "^Workspace [0-9]\+" | sed -rn 's/Workspace ([0-9]+).*/\1/p' | sort -n)
}

active_workspaces_including()
{
	local list=$(echo $@ | sed 's/ /\\|/g')
	echo $(active_workspaces | tr '[:space:]' '\n' | grep $list)
}

active_workspaces_excluding()
{
	local list=$(echo $@ | sed 's/ /\\|/g')
	echo $(active_workspaces | tr '[:space:]' '\n' | grep -v $list)
}
