#! perl -w

sub on_user_command {
    my ($self, $cmd) = @_;
	my $output = "";

	if ($cmd eq "dynamic-colors:cycle") {
		$output = `\$HOME/.dynamic-colors/bin/dynamic-colors cycle`;
		$self->cmd_parse($output);
	} else {
		(my $scheme = $cmd) =~ s/dynamic-colors://g;
		unless (-e "$ENV{'HOME'}/.dynamic-colors/colorschemes/$scheme.sh") {
			return;
		}
		$output = `\$HOME/.dynamic-colors/bin/dynamic-colors switch $scheme`;
		$self->cmd_parse($output);
	}
}
